### ISSUE TITLE
Also use IPv6 Google DNS

### ISSUE THREAD

**Issue by Mikaela** [tfae/magisk-google-dns#1]
If I understood correctly, this only sets IPv4 DNS servers forgetting IPv6 entirely even ifnit's supported by Google DNS.

> 2001:4860:4860::8888
> 2001:4860:4860::8844

https://developers.google.com/speed/public-dns/docs/using#google_public_dns_ip_addresses

**Comment by ghost** [comment]
Exactly. And only uses 8888 and not 8844.
